export const ApiMethodNames = {
  GetAllCategories: "GetAllCategories",
  Getallmenusbyrole: "Getallmenusbyrole",
  GetAllUsersDetails: "GetAllUsersDetails",
  GetAllApprTypes: "GetAllApprTypes",
  GetAllApprSettings: "GetAllApprSettings",
  SaveApprovalSettingsUpdateDelete: "SaveApprovalSettingsUpdateDelete",
  SaveDefaultRole: "SaveDefaultRole",
  GetCity: "GetCity",
  GetCountry: "GetCountry",
  GetState: "GetState",
  GetUserProfileById: "GetUserProfileById",
  SaveUpdateUserProfile: "SaveUpdateUserProfile",
  GetAllProductsForAdmin: "GetAllProductsForAdmin",
  SaveUpdateDeleteProduct: "SaveUpdateDeleteProduct",
  GetProductByIdAdmin: "GetProductByIdAdmin",
} as const;
